### PR TITLE
add acrn-kernel 5.4 && remove paths-master patch 

### PR DESCRIPTION
**Pull request by wenlingz**
Signed-off-by: wenlingz <wenling.zhang@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
@saininav  please help review and merge this patch, thanks.

**Comment by moto-timo** [comment]
This PR cannot be merged as is. There are multiple issues. See my comments above.

**Comment by wenlingz** [comment]
@cheeyanglee  could you give some advice ?

**Comment by wenlingz** [comment]
close it

**Pull request closed without merging**
