### PR TITLE
Kernel: Enable vsock kernel config in Service VM 

### PR DESCRIPTION
**Pull request by wenlingz**
kernel: Enable vsock kernel config in Service VM 

Signed-off-by: wenlingz <wenling.zhang@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
On a separate note, could we rename these config fragment files to use `user_vm` and `service_vm` instead of `uos` and `sos`?

**Comment by wenlingz** [comment]
@saininav please help review and merge it, thanks

**Comment by saininav** [comment]
I can see only missing configuration is CONFIG_VHOST_VSOCK.

Can you update your PR for this only !

**Comment by saininav** [comment]
> On a separate note, could we rename these config fragment files to use `user_vm` and `service_vm` instead of `uos` and `sos`?

@gvancuts Sure, I will raise new PR for this modification !

**Pull request merged**
