### PR TITLE
Acrn1.3

### PR DESCRIPTION
**Pull request by cheeyanglee**
update to acrn 1.3  and  kernel 4.19.73-base-190919T160721Z

### CODE REVIEW

**Comment by cheeyanglee** [comment]
any comment?

**Comment by rossburton** [comment]
I've merged the kernel upgrade.  The ACRN upgrade I'm not sure about the use of a class, as it's just a few variables with default values.

Might be neater to just add those as defaults to the `layer.conf`?

**Comment by cheeyanglee** [comment]
would this be better?
https://github.com/cheeyanglee/meta-acrn/commit/b55d0d9f96569c6c2a458b446084f9a7853d3b34
this basically create a relative link name acrn.efi to the acrn.${ACRN_BOARD}.${ACRN_SCENARIO}.efi so that conversion for wic.acrn doesnt need ACRN_BOARD and ACRN_SCENARIO

**Comment by cheeyanglee** [comment]
> [cheeyanglee@b55d0d9](https://github.com/cheeyanglee/meta-acrn/commit/b55d0d9f96569c6c2a458b446084f9a7853d3b34)

btw this also allow to set SCENARIO for build, which is not included in https://github.com/intel/meta-acrn/pull/25/commits/c5acc9a653bb1fd5f46ed6e727fbef45aa5d1376
see this line :
https://github.com/cheeyanglee/meta-acrn/commit/b55d0d9f96569c6c2a458b446084f9a7853d3b34#diff-6188371a3b4b96178ba7e65fa44706e4R10

**Comment by saininav** [comment]
Hi Ross/Chin Huat, I need below patch in acrn-hypervisor, which is already merged in 1.3 release.
https://github.com/projectacrn/acrn-hypervisor/commit/2d57c5feb758e9092fad649dc063fedef5c479c3

Do you have any comments on Chee Yang's patch for 1.3 upgrade ? cheeyanglee@b55d0d9

If no, can you please merge Chee Yang's patch.

**Comment by cheeyanglee** [comment]
This uses 'lnr' instead 
https://github.com/cheeyanglee/meta-acrn/commit/2a94a6faf6b56f58e2d8c0a22a4f69ca18d9f240

**Comment by rossburton** [comment]
https://github.com/cheeyanglee/meta-acrn/commit/2a94a6faf6b56f58e2d8c0a22a4f69ca18d9f240 merged.

**Pull request closed without merging**
