### PR TITLE
rt-5.4-config: Enable virtio polling mode for RT kernel

### PR DESCRIPTION
**Pull request by shuox**
CONFIG_VIRTIO_PMD is used to enable polling mode for virtio frontend
drviers. It's needed by a real-time kernel because the
backend-to-frontend notify interrupts can be saved.

Signed-off-by: Shuo A Liu <shuo.a.liu@intel.com>

### CODE REVIEW

**Comment by shuox** [comment]
@wenlingz

**Comment by wenlingz** [comment]
@saininav please help review and merge
@shuox please help create new one on master-next branch, thanks

**Comment by saininav** [comment]
> CONFIG_VIRTIO_PMD is used to enable polling mode for virtio frontend
> drviers. It's needed by a real-time kernel because the
> backend-to-frontend notify interrupts can be saved.
> 
> Signed-off-by: Shuo A Liu [shuo.a.liu@intel.com](mailto:shuo.a.liu@intel.com)



> @wenlingz

From the short description, it seems, it is applicable only for rt-5.4 ?

**Comment by wenlingz** [comment]
> > CONFIG_VIRTIO_PMD is used to enable polling mode for virtio frontend
> > drviers. It's needed by a real-time kernel because the
> > backend-to-frontend notify interrupts can be saved.
> > Signed-off-by: Shuo A Liu [shuo.a.liu@intel.com](mailto:shuo.a.liu@intel.com)
> 
> > @wenlingz
> 
> From the short description, it seems, it is applicable only for rt-5.4 ?

YES

**Pull request merged**
