### PR TITLE
sos.cfg: set CONFIG_VHOST_NET and CONFIG_VHOST

### PR DESCRIPTION
**Pull request by gaojunhao0504**
This configuration allows to enable vhost net.

Signed-off-by: Gao Junhao <junhao.gao@intel.com>

### CODE REVIEW

**Comment by anujm1** [comment]
Would it be better to use something like instead:

KERNEL_FEATURES_append = " features/kvm/qemu-kvm-enable.scc"

**Comment by wenlingz** [comment]
> Would it be better to use something like instead: KERNEL_FEATURES_append = " features/kvm/qemu-kvm-enable.scc"

Actually YES, please refer https://github.com/intel/meta-acrn/blob/master/recipes-kernel/linux/files/sos_4.19.scc,  sos.cfg is in sos_4.19.scc

**Comment by cheeyanglee** [comment]
> > Would it be better to use something like instead: KERNEL_FEATURES_append = " features/kvm/qemu-kvm-enable.scc"
> 
> Actually YES, please refer https://github.com/intel/meta-acrn/blob/master/recipes-kernel/linux/files/sos_4.19.scc, sos.cfg is in sos_4.19.scc

is this for 4.19 kernel only?

**Comment by wenlingz** [comment]
> > > Would it be better to use something like instead: KERNEL_FEATURES_append = " features/kvm/qemu-kvm-enable.scc"
> > 
> > 
> > Actually YES, please refer https://github.com/intel/meta-acrn/blob/master/recipes-kernel/linux/files/sos_4.19.scc, sos.cfg is in sos_4.19.scc
> 
> is this for 4.19 kernel only?

NO, both for 4.19 and 5.4

**Comment by saininav** [comment]
Rebased the patch and merged.
https://github.com/intel/meta-acrn/commit/3336932e07ce4cac3b9daa9236bebd01cdf7119c

**Pull request closed without merging**
