### PR TITLE
upgrade to acrn 1.1

### PR DESCRIPTION
**Pull request by cheeyanglee**
these patches
1. upgrade acrn recipes to acrn 1.1
2. update docs to use variable for path

### CODE REVIEW

**Comment by ChinHuatAng** [comment]
We probably should wait for ACRN v1.1 release before merging this.

**Comment by rossburton** [comment]
Yes, we'll wait for the 1.1 release announcement, but thanks for the proactive upgrade so we can merge this when it's ready.

I've picked the documentation fix to master.

**Comment by ChinHuatAng** [comment]
ACRN v1.1 is now available: https://projectacrn.org/acrn-project-releases-version-1-1/

Please be sure to update the SRCREV.

**Comment by ChinHuatAng** [comment]
On NUC7i7DNH1E, glmark2 score for SOS seems to have reduced drastically.

acrn-hypervisor & linux-intel-acrn -- v1.0 + PK 4.19.36 --> v1.1 + PK 4.19.55

native -- 2677 --> 2675 (+0%)
SOS -- 2339 --> 1010 (-57%)
UOS -- 1862 --> 1693 (-9%)

SOS/native -- 87% --> 38%
UOS/SOS -- 80% --> 167%
UOS/native -- 70% --> 63%

**Comment by rossburton** [comment]
Oh that’s not good. Can you isolate it to the kernel or acrn upgrade?

**Comment by ChinHuatAng** [comment]
Let me check v1.0 + PK 4.19.55 or any prior versions, that should give us some data points.

**Comment by rossburton** [comment]
Did anyone manage to determine if the GL regression was the new kernel or ACRN 1.1?

**Pull request merged**
