### PR TITLE
Add dependency cjson and update to tag acrn-2022w11.3-180000p

### PR DESCRIPTION
**Pull request by wenlingz**
Add dependency cjson and update to ACRN tag acrn-2022w11.3-180000p
Signed-off-by: wenlingz <wenling.zhang@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
@saininav please help review and approve it, thanks

**Comment by saininav** [comment]
Hi Wenling, 
Sorry for delay, I was on leave !
I am facing build failure while testing this PR with openssl3.0. Fix is already available in release_2.7 branch. Is there any plan to take following patch in master:
https://github.com/projectacrn/acrn-hypervisor/commit/430fc6327dbe0bc262121619baa35693197d9a67

**Comment by wenlingz** [comment]
> 

OK， got it, thanks

**Comment by wenlingz** [comment]
@saininav please help check, thanks

**Comment by cheeyanglee** [comment]
keep this as notes here. 
-A and mac_seed option dropped from acrn-dm, remove only these option from current launch script will hung the system while launching UOS (on NUC11TNH).
There are known issue with config tools, so generate a sample launch script are not possible at this point. ( https://github.com/projectacrn/acrn-hypervisor/issues/7161 ) , 
we will need to update launch script later.

**Pull request closed without merging**
