### PR TITLE
kernel to linux intel 

### PR DESCRIPTION
**Pull request by cheeyanglee**

### CODE REVIEW

**Comment by saininav** [comment]
Not sure, if we want to set sos/uos labeling  !

linux-intel-acrn-sos_4.19.bb: 
LINUX_VERSION_EXTENSION ?= "-linux-intel-acrn-sos"

linux-intel-acrn-uos_4.19.bb
LINUX_VERSION_EXTENSION ?= "linux-intel-acrn-uos"

**Comment by cheeyanglee** [comment]
> Not sure, if we want to set sos/uos labeling !
> 
> linux-intel-acrn-sos_4.19.bb:
> LINUX_VERSION_EXTENSION ?= "-linux-intel-acrn-sos"
> 
> linux-intel-acrn-uos_4.19.bb
> LINUX_VERSION_EXTENSION ?= "linux-intel-acrn-uos"

would make this a separate patch as it is not a must

**Comment by rossburton** [comment]
I would add the version extension, yes.  Also the layer dependency on meta-intel should be in this pull request too.

**Comment by cheeyanglee** [comment]
> I would add the version extension, yes. Also the layer dependency on meta-intel should be in this pull request too.

added one more commit to include LINUX_VERSION_EXTENSION. 
layer dependency are here https://github.com/intel/meta-acrn/pull/34

**Comment by saininav** [comment]
Hi Ross, Can you merge this patch?

**Comment by rossburton** [comment]
Squashed, and merged in 19d24d1dd7aed2449e3ad09cef23849bc9cfc220.

**Pull request closed without merging**
