### PR TITLE
docs: specify virtual/kernel

### PR DESCRIPTION
**Pull request by cheeyanglee**
soft assigned virtual/kernel might result in linux-intel as virtualkernel. 
its better to include virtual/kernel in local.conf.

Signed-off-by: Chee Yang Lee <chee.yang.lee@intel.com>

### CODE REVIEW

**Comment by rossburton** [comment]
I think I prefer changing the demo distro configs to assign, and if the user wants to use a different kernel (such as -rt) then they hard-assign in local.conf (or write their own distro).

**Comment by cheeyanglee** [comment]
```
# $PREFERRED_PROVIDER_virtual/kernel [4 operations]
#   set? /data/yocto/poky-master/meta-intel/conf/machine/include/meta-intel.inc:7
#     "linux-intel"
#   set /data/yocto/poky-master/meta/conf/machine/include/x86-base.inc:20
#     [_defaultval] "linux-yocto"
#   set? /data/yocto/poky-master/meta-acrn/conf/distro/acrn-demo-sos.conf:6
#     "linux-intel-acrn-sos"
#   override[poky-tiny]:set? /data/yocto/poky-master/meta-intel/conf/machine/include/meta-intel.inc:8
#     "linux-intel"
# pre-expansion value:
#   "linux-intel"
PREFERRED_PROVIDER_virtual/kernel="linux-intel"
```

seems like MACHINE overrides has higher priority than DISTRO.

**Comment by cheeyanglee** [comment]
please review only https://github.com/intel/meta-acrn/commit/db2ecad3126db9505bf3f2342ce7d6ed9373c4db and ignore other commits.

**Comment by cheeyanglee** [comment]
close the pull request as it mixed with unnecessary commit and causes confuses. make it in another pull request.

**Pull request closed without merging**
