### PR TITLE
linux-intel-rt/4.19: introduce preempt-RT kernel for UOS

### PR DESCRIPTION
**Pull request by saininav**
This bbappend enables linux-intel preempt-RT kernel for real-time
uos (RTVM).
Currently pointing to Linux stable v4.19.59 and -rt24 patchset.

To enable RT kernel for uos, add below in uos.conf:
PREFERRED_PROVIDER_virtual/kernel = "linux-intel-rt"
PREFERRED_VERSION_linux-intel-rt = "4.19%"

Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>

### CODE REVIEW

**Comment by cheeyanglee** [comment]
existing .travis.yml does not include meta-intel 

this should fix the Travis CI build.
https://github.com/cheeyanglee/meta-acrn/commit/b3adeee44804f7e04f330b1526b7e5d6937e46e0

**Comment by saininav** [comment]
> existing .travis.yml does not include meta-intel
> 
> this should fix the Travis CI build.
> [cheeyanglee@b3adeee](https://github.com/cheeyanglee/meta-acrn/commit/b3adeee44804f7e04f330b1526b7e5d6937e46e0)

Can you raise pull request for this too !

**Comment by saininav** [comment]
Ping

**Comment by rossburton** [comment]
Merged the distro conf patch, as that is obviously correct.

**Comment by rossburton** [comment]
This should add a layer dependency on meta-intel (in `layer.conf`) as it bbappends a recipe from meta-intel.

**Comment by rossburton** [comment]
*However* I'm not sure we should be bbappending the kernel globally if the recipe is included.  Maybe create a new recipe that includes the linux-intel-rt recipe and then fiddles the configuration?

**Comment by saininav** [comment]
> _However_ I'm not sure we should be bbappending the kernel globally if the recipe is included. Maybe create a new recipe that includes the linux-intel-rt recipe and then fiddles the configuration?

Yes, I was also not sure, so first created new recipe, but later I made the decision based on:
(1) In given https://projectacrn.github.io/1.2/tutorials/rt_linux.html reference, they do not pick specific RT-kernel version and does not apply any acrn specific patches, so I assumed, any RT kernel will work. But agreed, it will need testing on every kernel upgrade in meta-intel. If we do timely release(branching) along with meta-intel. It would be fine. 

But somehow i also think, that new recipe will be more safe!

Should we create new recipe and point to only kernel version used by acrn-kernel ?
https://github.com/projectacrn/acrn-kernel/commits/4.19/preempt-rt

**Comment by saininav** [comment]
> This should add a layer dependency on meta-intel (in `layer.conf`) as it bbappends a recipe from meta-intel.

Agreed I will do accordingly.

**Comment by saininav** [comment]
> > _However_ I'm not sure we should be bbappending the kernel globally if the recipe is included. Maybe create a new recipe that includes the linux-intel-rt recipe and then fiddles the configuration?
> 
> Yes, I was also not sure, so first created new recipe, but later I made the decision based on:
> (1) In given https://projectacrn.github.io/1.2/tutorials/rt_linux.html reference, they do not pick specific RT-kernel version and does not apply any acrn specific patches, so I assumed, any RT kernel will work. But agreed, it will need testing on every kernel upgrade in meta-intel. If we do timely release(branching) along with meta-intel. It would be fine.
> 
> But somehow i also think, that new recipe will be more safe!
> 
> Should we create new recipe and point to only kernel version used by acrn-kernel ?
> https://github.com/projectacrn/acrn-kernel/commits/4.19/preempt-rt

I just understood, what do you mean. Please ignore this.

**Pull request closed without merging**
